# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
stages:
 - stage: Build
   jobs:
   - job: Build

   pool:
     vmImage: ubuntu-latest

   variables:
     buildConfiguration: 'Release'

     steps:
     - script: dotnet build --configuration $(buildConfiguration)
       displayName: 'dotnet build $(buildConfiguration)'

     - task: PublishBuildArtifacts@1
       inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
     - stage: Deploy
       jobs:
       - job: Deploy
       pool:
       vmImage: ubuntu-latest
       steps:
       - task: DownloadBuildArtifacts@0
         inputs:
           buildType: 'current'
           downloadType: 'single'
           artifactName: 'drop'         
           downloadPath: '$(System.ArtifactsDirectory)'

       - task: AzureRmWebAppDeployment@4
         inputs:
           ConnectionType: 'AzureRM'
           azureSubscription: 'NewServiceConnection001'
           appType: 'webApp'
           WebAppName: 
           packageForLinux: '$(System.ArtifactsDirectory)/drop/*.zip'