# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

stages:
 - stage: Build
   jobs:
   - job: Build
     pool:
      vmImage: 'windows-latest'

      variables:
        solution: '**/*.sln'
        buildPlatform: 'Any CPU'
        buildConfiguration: 'Release'
        
      steps:
      - task: NuGetToolInstaller@1

      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$(solution)'

      - task: VSBuild@1
        inputs:
          solution: '$(solution)'
          msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'

      - task: VSTest@2
        inputs:
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)' 
            
      - task: PublishBuildArtifacts@1        
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop1'
        publishLocation: 'Container'
        
 - stage: Deploy
   jobs:
   - job: Deploy
     pool:
      vmImage: 'windows-latest'
        
     steps:     
     - task: DownloadBuildArtifacts@0
       displayName : Download Artifacts(*.zip)
       inputs:         
         buildType: 'current'
         downloadType: 'specific'
         artifactName: 'drop1'         
         downloadPath: '$(System.ArtifactsDirectory)'
         
     - task: AzureRmWebAppDeployment@4
       inputs:
         ConnectionType: 'AzureRM'
         azureSubscription: 'NewServiceConnection001'
         appType: 'webApp'
         WebAppName: 'devopscicd1-dev'
         packageForLinux: '$(System.ArtifactsDirectory)/drop1/*.zip'